=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CrosslyBuyer::CreateAiGenerateListingResponsePriceRange
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CrosslyBuyer::CreateAiGenerateListingResponsePriceRange do
  let(:instance) { CrosslyBuyer::CreateAiGenerateListingResponsePriceRange.new }

  describe 'test an instance of CreateAiGenerateListingResponsePriceRange' do
    it 'should create an instance of CreateAiGenerateListingResponsePriceRange' do
      expect(instance).to be_instance_of(CrosslyBuyer::CreateAiGenerateListingResponsePriceRange)
    end
  end
  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "confidence"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
