=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CrosslyBuyer::GetAnalyticBookkeepingResponseMonthlyPL
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CrosslyBuyer::GetAnalyticBookkeepingResponseMonthlyPL do
  let(:instance) { CrosslyBuyer::GetAnalyticBookkeepingResponseMonthlyPL.new }

  describe 'test an instance of GetAnalyticBookkeepingResponseMonthlyPL' do
    it 'should create an instance of GetAnalyticBookkeepingResponseMonthlyPL' do
      expect(instance).to be_instance_of(CrosslyBuyer::GetAnalyticBookkeepingResponseMonthlyPL)
    end
  end
  describe 'test attribute "month"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "revenue"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "cogs"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "platform_fees"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "shipping_costs"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "net_profit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
