=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CrosslyBuyer::GetSpatialSceneResponseBreakdowns
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CrosslyBuyer::GetSpatialSceneResponseBreakdowns do
  let(:instance) { CrosslyBuyer::GetSpatialSceneResponseBreakdowns.new }

  describe 'test an instance of GetSpatialSceneResponseBreakdowns' do
    it 'should create an instance of GetSpatialSceneResponseBreakdowns' do
      expect(instance).to be_instance_of(CrosslyBuyer::GetSpatialSceneResponseBreakdowns)
    end
  end
  describe 'test attribute "facet"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["brand", "condition", "size", "status", "label", "title", "value", "year", "grade", "set", "franchise", "game", "team", "era", "genre", "colour", "age"])
      # validator.allowable_values.each do |value|
      #   expect { instance.facet = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "distinct"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
