=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CrosslyBuyer::GetTaxonomyRequiredFieldResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe CrosslyBuyer::GetTaxonomyRequiredFieldResponse do
  let(:instance) { CrosslyBuyer::GetTaxonomyRequiredFieldResponse.new }

  describe 'test an instance of GetTaxonomyRequiredFieldResponse' do
    it 'should create an instance of GetTaxonomyRequiredFieldResponse' do
      expect(instance).to be_instance_of(CrosslyBuyer::GetTaxonomyRequiredFieldResponse)
    end
  end
  describe 'test attribute "platform"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ebay", "etsy", "poshmark", "mercari", "depop", "grailed", "vinted", "whatnot", "vestiaire", "offerup", "facebook", "curtsy"])
      # validator.allowable_values.each do |value|
      #   expect { instance.platform = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "required_fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
