=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module Crossly
  class CreateBuyerCartQuoteResponse
    attr_accessor :kind

    attr_accessor :tax_cents

    attr_accessor :shipping_cents

    attr_accessor :total_cents

    attr_accessor :currency

    attr_accessor :items_total_cents

    # Lines being collected in person, so a summary can name what ships free.
    attr_accessor :pickup_cart_item_ids

    # False means there is no saved delivery address, so `taxCents` is a floor rather than a final figure — not that tax is zero.
    attr_accessor :tax_complete

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'kind' => :'kind',
        :'tax_cents' => :'taxCents',
        :'shipping_cents' => :'shippingCents',
        :'total_cents' => :'totalCents',
        :'currency' => :'currency',
        :'items_total_cents' => :'itemsTotalCents',
        :'pickup_cart_item_ids' => :'pickupCartItemIds',
        :'tax_complete' => :'taxComplete'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'kind' => :'String',
        :'tax_cents' => :'Float',
        :'shipping_cents' => :'Float',
        :'total_cents' => :'Float',
        :'currency' => :'String',
        :'items_total_cents' => :'Float',
        :'pickup_cart_item_ids' => :'Array<String>',
        :'tax_complete' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crossly::CreateBuyerCartQuoteResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crossly::CreateBuyerCartQuoteResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'kind')
        self.kind = attributes[:'kind']
      end

      if attributes.key?(:'tax_cents')
        self.tax_cents = attributes[:'tax_cents']
      end

      if attributes.key?(:'shipping_cents')
        self.shipping_cents = attributes[:'shipping_cents']
      end

      if attributes.key?(:'total_cents')
        self.total_cents = attributes[:'total_cents']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'items_total_cents')
        self.items_total_cents = attributes[:'items_total_cents']
      end

      if attributes.key?(:'pickup_cart_item_ids')
        if (value = attributes[:'pickup_cart_item_ids']).is_a?(Array)
          self.pickup_cart_item_ids = value
        end
      end

      if attributes.key?(:'tax_complete')
        self.tax_complete = attributes[:'tax_complete']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @kind.nil?
        invalid_properties.push('invalid value for "kind", kind cannot be nil.')
      end

      if @tax_cents.nil?
        invalid_properties.push('invalid value for "tax_cents", tax_cents cannot be nil.')
      end

      if @shipping_cents.nil?
        invalid_properties.push('invalid value for "shipping_cents", shipping_cents cannot be nil.')
      end

      if @total_cents.nil?
        invalid_properties.push('invalid value for "total_cents", total_cents cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @items_total_cents.nil?
        invalid_properties.push('invalid value for "items_total_cents", items_total_cents cannot be nil.')
      end

      if @pickup_cart_item_ids.nil?
        invalid_properties.push('invalid value for "pickup_cart_item_ids", pickup_cart_item_ids cannot be nil.')
      end

      if @tax_complete.nil?
        invalid_properties.push('invalid value for "tax_complete", tax_complete cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @kind.nil?
      return false if @tax_cents.nil?
      return false if @shipping_cents.nil?
      return false if @total_cents.nil?
      return false if @currency.nil?
      return false if @items_total_cents.nil?
      return false if @pickup_cart_item_ids.nil?
      return false if @tax_complete.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          kind == o.kind &&
          tax_cents == o.tax_cents &&
          shipping_cents == o.shipping_cents &&
          total_cents == o.total_cents &&
          currency == o.currency &&
          items_total_cents == o.items_total_cents &&
          pickup_cart_item_ids == o.pickup_cart_item_ids &&
          tax_complete == o.tax_complete
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [kind, tax_cents, shipping_cents, total_cents, currency, items_total_cents, pickup_cart_item_ids, tax_complete].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crossly.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
