=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module Crossly
  class CreateListingImportByUrlResponseListing
    attr_accessor :platform_listing_id

    attr_accessor :title

    attr_accessor :description

    attr_accessor :price

    attr_accessor :images

    attr_accessor :brand

    attr_accessor :condition

    attr_accessor :size

    # Color(s) the platform's own response exposes (e.g. Poshmark's  `colors` array). Only set when actually present in the scrape.
    attr_accessor :color

    attr_accessor :sku

    attr_accessor :url

    # The platform's OWN category, as a top-down path (e.g. Poshmark's  [\"Kids\", \"Toys\", \"Dolls & Accessories\"] from department → category →  feature). Only set when the platform's list/scrape response actually  carries this — never guessed. Mapped onto Crossly's category.main/  sub/sub2 (listings) or categoryMain/categorySub (inventory_items) at  create/enrich time.
    attr_accessor :category

    # The platform's raw numeric category id, same space as  overrides.<platform>.categoryId — distinct from `category`'s  human-readable path. Only set by platforms whose id space is directly  comparable to what we publish (currently eBay's drift-check second  call — see diff-fields/second-call.ts's ebayRemoteFields). eBay's own  CategoryName wording/depth is a different vocabulary from Crossly's  master taxonomy breadcrumb and will essentially never string-match  it, so drift-detection compares ids instead of names.
    attr_accessor :category_id

    # Tag-like strings the platform's own response exposes (e.g. Poshmark's  marketing \"experience\" tags). Distinct from a full search-tag  generator — just whatever real tag data the scrape already carries.
    attr_accessor :tags

    # Structured item aspects — the same shape the listing form's Item  Details section captures (and templates already persist), now sourced  from the platform's own data instead of only manual entry. Only set  when the platform's response genuinely carries a semantically-matching  field (eBay item specifics, Facebook attributes, Poshmark catalog,  Depop's detail-call ride-along) — never derived or guessed.
    attr_accessor :material

    attr_accessor :style

    attr_accessor :pattern

    attr_accessor :department

    attr_accessor :gender

    attr_accessor :item_type

    attr_accessor :size_system

    # Category-specific facets from a per-item DETAIL call (e.g. Facebook's  Age Range/Character/Age Group), keyed the same way eBay item-specifics  are: aspect name -> value array. Only set by platforms with a genuine  per-item attribute source — costs one extra call per listing, so  populated by a dedicated enrichment pass, not the main list mapper.  Maps onto listings.itemSpecifics; inventory_items has no equivalent  column.
    attr_accessor :item_specifics

    # When the listing was first published on the platform. Used by  the Advanced filter's listedAfter / listedBefore knobs. Optional  because not every platform returns it on the listing endpoint.
    attr_accessor :listed_at

    # Units this platform reports. Only meaningful for platforms  `PLATFORM_QUANTITY_SYNC` marks 'native' — relist platforms show one item  and say 1 forever, so they leave this undefined rather than voting with  a number they cannot actually express. See `_quantity.ts`.
    attr_accessor :quantity

    # Which of the user's connected accounts on this platform this listing  was scraped from — stamped by fetchCookieListings as it loops each  connected account (see listActiveForPlatform in  user-platform-accounts/read.ts). Undefined for API-track platforms  (single connection, no multi-account concept) and for any cookie path  that hasn't been threaded yet; importOne treats undefined as slot 1,  matching the historical single-account default.
    attr_accessor :account_slot

    # Total item weight in ounces (already summed, not split lb+oz —  the write path converts to the DB's weightLb+weightOz split).
    attr_accessor :weight_oz

    attr_accessor :dimension_lin

    attr_accessor :dimension_win

    attr_accessor :dimension_hin

    # Max days the platform's own listing commits to ship within (eBay's  DispatchTimeMax, Etsy's processing_max).
    attr_accessor :handling_time_days

    attr_accessor :best_offer_auto_accept_cents

    attr_accessor :best_offer_auto_decline_cents

    # Free text as the platform itself expresses it (e.g. eBay's `Location`  is a single seller-typed string like \"Austin, TX\", not a structured  address) — never parsed into city/state.
    attr_accessor :item_location

    attr_accessor :item_location_zip

    attr_accessor :item_location_country

    # What the platform's OWN listing declares shipping costs — reference  only, distinct from a realized post-sale shipping cost.
    attr_accessor :declared_shipping_cost

    attr_accessor :return_policy_text

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'platform_listing_id' => :'platformListingId',
        :'title' => :'title',
        :'description' => :'description',
        :'price' => :'price',
        :'images' => :'images',
        :'brand' => :'brand',
        :'condition' => :'condition',
        :'size' => :'size',
        :'color' => :'color',
        :'sku' => :'sku',
        :'url' => :'url',
        :'category' => :'category',
        :'category_id' => :'categoryId',
        :'tags' => :'tags',
        :'material' => :'material',
        :'style' => :'style',
        :'pattern' => :'pattern',
        :'department' => :'department',
        :'gender' => :'gender',
        :'item_type' => :'itemType',
        :'size_system' => :'sizeSystem',
        :'item_specifics' => :'itemSpecifics',
        :'listed_at' => :'listedAt',
        :'quantity' => :'quantity',
        :'account_slot' => :'accountSlot',
        :'weight_oz' => :'weightOz',
        :'dimension_lin' => :'dimensionLIn',
        :'dimension_win' => :'dimensionWIn',
        :'dimension_hin' => :'dimensionHIn',
        :'handling_time_days' => :'handlingTimeDays',
        :'best_offer_auto_accept_cents' => :'bestOfferAutoAcceptCents',
        :'best_offer_auto_decline_cents' => :'bestOfferAutoDeclineCents',
        :'item_location' => :'itemLocation',
        :'item_location_zip' => :'itemLocationZip',
        :'item_location_country' => :'itemLocationCountry',
        :'declared_shipping_cost' => :'declaredShippingCost',
        :'return_policy_text' => :'returnPolicyText'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'platform_listing_id' => :'String',
        :'title' => :'String',
        :'description' => :'String',
        :'price' => :'Float',
        :'images' => :'Array<String>',
        :'brand' => :'String',
        :'condition' => :'String',
        :'size' => :'String',
        :'color' => :'Array<String>',
        :'sku' => :'String',
        :'url' => :'String',
        :'category' => :'Array<String>',
        :'category_id' => :'String',
        :'tags' => :'Array<String>',
        :'material' => :'String',
        :'style' => :'String',
        :'pattern' => :'String',
        :'department' => :'String',
        :'gender' => :'String',
        :'item_type' => :'String',
        :'size_system' => :'String',
        :'item_specifics' => :'Object',
        :'listed_at' => :'Time',
        :'quantity' => :'Float',
        :'account_slot' => :'Float',
        :'weight_oz' => :'Float',
        :'dimension_lin' => :'Float',
        :'dimension_win' => :'Float',
        :'dimension_hin' => :'Float',
        :'handling_time_days' => :'Float',
        :'best_offer_auto_accept_cents' => :'Float',
        :'best_offer_auto_decline_cents' => :'Float',
        :'item_location' => :'String',
        :'item_location_zip' => :'String',
        :'item_location_country' => :'String',
        :'declared_shipping_cost' => :'Float',
        :'return_policy_text' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'price',
        :'images',
        :'brand',
        :'condition',
        :'size',
        :'color',
        :'sku',
        :'url',
        :'category',
        :'category_id',
        :'tags',
        :'material',
        :'style',
        :'pattern',
        :'department',
        :'gender',
        :'item_type',
        :'size_system',
        :'item_specifics',
        :'listed_at',
        :'quantity',
        :'account_slot',
        :'weight_oz',
        :'dimension_lin',
        :'dimension_win',
        :'dimension_hin',
        :'handling_time_days',
        :'best_offer_auto_accept_cents',
        :'best_offer_auto_decline_cents',
        :'item_location',
        :'item_location_zip',
        :'item_location_country',
        :'declared_shipping_cost',
        :'return_policy_text'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crossly::CreateListingImportByUrlResponseListing` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crossly::CreateListingImportByUrlResponseListing`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'platform_listing_id')
        self.platform_listing_id = attributes[:'platform_listing_id']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      end

      if attributes.key?(:'images')
        if (value = attributes[:'images']).is_a?(Array)
          self.images = value
        end
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'condition')
        self.condition = attributes[:'condition']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'color')
        if (value = attributes[:'color']).is_a?(Array)
          self.color = value
        end
      end

      if attributes.key?(:'sku')
        self.sku = attributes[:'sku']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'category')
        if (value = attributes[:'category']).is_a?(Array)
          self.category = value
        end
      end

      if attributes.key?(:'category_id')
        self.category_id = attributes[:'category_id']
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'material')
        self.material = attributes[:'material']
      end

      if attributes.key?(:'style')
        self.style = attributes[:'style']
      end

      if attributes.key?(:'pattern')
        self.pattern = attributes[:'pattern']
      end

      if attributes.key?(:'department')
        self.department = attributes[:'department']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      end

      if attributes.key?(:'item_type')
        self.item_type = attributes[:'item_type']
      end

      if attributes.key?(:'size_system')
        self.size_system = attributes[:'size_system']
      end

      if attributes.key?(:'item_specifics')
        self.item_specifics = attributes[:'item_specifics']
      end

      if attributes.key?(:'listed_at')
        self.listed_at = attributes[:'listed_at']
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      end

      if attributes.key?(:'account_slot')
        self.account_slot = attributes[:'account_slot']
      end

      if attributes.key?(:'weight_oz')
        self.weight_oz = attributes[:'weight_oz']
      end

      if attributes.key?(:'dimension_lin')
        self.dimension_lin = attributes[:'dimension_lin']
      end

      if attributes.key?(:'dimension_win')
        self.dimension_win = attributes[:'dimension_win']
      end

      if attributes.key?(:'dimension_hin')
        self.dimension_hin = attributes[:'dimension_hin']
      end

      if attributes.key?(:'handling_time_days')
        self.handling_time_days = attributes[:'handling_time_days']
      end

      if attributes.key?(:'best_offer_auto_accept_cents')
        self.best_offer_auto_accept_cents = attributes[:'best_offer_auto_accept_cents']
      end

      if attributes.key?(:'best_offer_auto_decline_cents')
        self.best_offer_auto_decline_cents = attributes[:'best_offer_auto_decline_cents']
      end

      if attributes.key?(:'item_location')
        self.item_location = attributes[:'item_location']
      end

      if attributes.key?(:'item_location_zip')
        self.item_location_zip = attributes[:'item_location_zip']
      end

      if attributes.key?(:'item_location_country')
        self.item_location_country = attributes[:'item_location_country']
      end

      if attributes.key?(:'declared_shipping_cost')
        self.declared_shipping_cost = attributes[:'declared_shipping_cost']
      end

      if attributes.key?(:'return_policy_text')
        self.return_policy_text = attributes[:'return_policy_text']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @platform_listing_id.nil?
        invalid_properties.push('invalid value for "platform_listing_id", platform_listing_id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @platform_listing_id.nil?
      return false if @title.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          platform_listing_id == o.platform_listing_id &&
          title == o.title &&
          description == o.description &&
          price == o.price &&
          images == o.images &&
          brand == o.brand &&
          condition == o.condition &&
          size == o.size &&
          color == o.color &&
          sku == o.sku &&
          url == o.url &&
          category == o.category &&
          category_id == o.category_id &&
          tags == o.tags &&
          material == o.material &&
          style == o.style &&
          pattern == o.pattern &&
          department == o.department &&
          gender == o.gender &&
          item_type == o.item_type &&
          size_system == o.size_system &&
          item_specifics == o.item_specifics &&
          listed_at == o.listed_at &&
          quantity == o.quantity &&
          account_slot == o.account_slot &&
          weight_oz == o.weight_oz &&
          dimension_lin == o.dimension_lin &&
          dimension_win == o.dimension_win &&
          dimension_hin == o.dimension_hin &&
          handling_time_days == o.handling_time_days &&
          best_offer_auto_accept_cents == o.best_offer_auto_accept_cents &&
          best_offer_auto_decline_cents == o.best_offer_auto_decline_cents &&
          item_location == o.item_location &&
          item_location_zip == o.item_location_zip &&
          item_location_country == o.item_location_country &&
          declared_shipping_cost == o.declared_shipping_cost &&
          return_policy_text == o.return_policy_text
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [platform_listing_id, title, description, price, images, brand, condition, size, color, sku, url, category, category_id, tags, material, style, pattern, department, gender, item_type, size_system, item_specifics, listed_at, quantity, account_slot, weight_oz, dimension_lin, dimension_win, dimension_hin, handling_time_days, best_offer_auto_accept_cents, best_offer_auto_decline_cents, item_location, item_location_zip, item_location_country, declared_shipping_cost, return_policy_text].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crossly.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
