=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module Crossly
  class GetListingResponsePlatformListings
    attr_accessor :id

    attr_accessor :user_id

    attr_accessor :quantity

    attr_accessor :status

    attr_accessor :platform

    attr_accessor :error_message

    attr_accessor :listing_id

    attr_accessor :account_slot

    attr_accessor :delisted_at

    attr_accessor :sold_at

    attr_accessor :inventory_item_id

    attr_accessor :platform_listing_id

    attr_accessor :platform_listing_url

    attr_accessor :stock_location

    attr_accessor :listed_at

    attr_accessor :shared_at

    attr_accessor :delist_reason

    attr_accessor :last_checked_at

    attr_accessor :views

    attr_accessor :favorites

    attr_accessor :comments_count

    attr_accessor :last_stats_synced_at

    attr_accessor :hashtags

    attr_accessor :is_draft

    attr_accessor :scheduled_publish_at

    attr_accessor :is_dutch_auction

    attr_accessor :dutch_start_cents

    attr_accessor :dutch_floor_cents

    attr_accessor :dutch_ends_at

    attr_accessor :is_pre_order

    attr_accessor :expected_ship_by

    attr_accessor :preorder_deposit_percent_bps

    attr_accessor :boosted_at

    attr_accessor :image_caption

    attr_accessor :duration_days

    attr_accessor :ends_at

    attr_accessor :best_offer_enabled

    attr_accessor :best_offer_auto_accept_cents

    attr_accessor :best_offer_auto_decline_cents

    attr_accessor :aesthetic_tags

    attr_accessor :allows_local_pickup

    attr_accessor :pickup_radius_miles

    attr_accessor :pickup_lat

    attr_accessor :pickup_lng

    attr_accessor :refurbished_tier

    attr_accessor :charity_slug

    attr_accessor :charity_percent_bps

    attr_accessor :crossly_return_policy_id

    attr_accessor :crossly_shipping_policy_id

    attr_accessor :crossly_payment_policy_id

    attr_accessor :retail_price_cents

    attr_accessor :restricted_countries

    attr_accessor :auction_extend_seconds

    attr_accessor :authentication_provider_slug

    attr_accessor :authentication_required

    attr_accessor :has_variants

    attr_accessor :charity_id

    attr_accessor :min_order_quantity

    attr_accessor :wholesale_unit_price_cents

    attr_accessor :wholesale_min_quantity

    attr_accessor :auction_reserve_cents

    attr_accessor :is_gtc

    attr_accessor :handling_time_days

    attr_accessor :item_location

    attr_accessor :item_location_zip

    attr_accessor :item_location_country

    attr_accessor :declared_shipping_cost

    attr_accessor :return_policy_text

    attr_accessor :last_drift_checked_at

    attr_accessor :verification_failed

    attr_accessor :published_overrides

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'user_id' => :'userId',
        :'quantity' => :'quantity',
        :'status' => :'status',
        :'platform' => :'platform',
        :'error_message' => :'errorMessage',
        :'listing_id' => :'listingId',
        :'account_slot' => :'accountSlot',
        :'delisted_at' => :'delistedAt',
        :'sold_at' => :'soldAt',
        :'inventory_item_id' => :'inventoryItemId',
        :'platform_listing_id' => :'platformListingId',
        :'platform_listing_url' => :'platformListingUrl',
        :'stock_location' => :'stockLocation',
        :'listed_at' => :'listedAt',
        :'shared_at' => :'sharedAt',
        :'delist_reason' => :'delistReason',
        :'last_checked_at' => :'lastCheckedAt',
        :'views' => :'views',
        :'favorites' => :'favorites',
        :'comments_count' => :'commentsCount',
        :'last_stats_synced_at' => :'lastStatsSyncedAt',
        :'hashtags' => :'hashtags',
        :'is_draft' => :'isDraft',
        :'scheduled_publish_at' => :'scheduledPublishAt',
        :'is_dutch_auction' => :'isDutchAuction',
        :'dutch_start_cents' => :'dutchStartCents',
        :'dutch_floor_cents' => :'dutchFloorCents',
        :'dutch_ends_at' => :'dutchEndsAt',
        :'is_pre_order' => :'isPreOrder',
        :'expected_ship_by' => :'expectedShipBy',
        :'preorder_deposit_percent_bps' => :'preorderDepositPercentBps',
        :'boosted_at' => :'boostedAt',
        :'image_caption' => :'imageCaption',
        :'duration_days' => :'durationDays',
        :'ends_at' => :'endsAt',
        :'best_offer_enabled' => :'bestOfferEnabled',
        :'best_offer_auto_accept_cents' => :'bestOfferAutoAcceptCents',
        :'best_offer_auto_decline_cents' => :'bestOfferAutoDeclineCents',
        :'aesthetic_tags' => :'aestheticTags',
        :'allows_local_pickup' => :'allowsLocalPickup',
        :'pickup_radius_miles' => :'pickupRadiusMiles',
        :'pickup_lat' => :'pickupLat',
        :'pickup_lng' => :'pickupLng',
        :'refurbished_tier' => :'refurbishedTier',
        :'charity_slug' => :'charitySlug',
        :'charity_percent_bps' => :'charityPercentBps',
        :'crossly_return_policy_id' => :'crosslyReturnPolicyId',
        :'crossly_shipping_policy_id' => :'crosslyShippingPolicyId',
        :'crossly_payment_policy_id' => :'crosslyPaymentPolicyId',
        :'retail_price_cents' => :'retailPriceCents',
        :'restricted_countries' => :'restrictedCountries',
        :'auction_extend_seconds' => :'auctionExtendSeconds',
        :'authentication_provider_slug' => :'authenticationProviderSlug',
        :'authentication_required' => :'authenticationRequired',
        :'has_variants' => :'hasVariants',
        :'charity_id' => :'charityId',
        :'min_order_quantity' => :'minOrderQuantity',
        :'wholesale_unit_price_cents' => :'wholesaleUnitPriceCents',
        :'wholesale_min_quantity' => :'wholesaleMinQuantity',
        :'auction_reserve_cents' => :'auctionReserveCents',
        :'is_gtc' => :'isGtc',
        :'handling_time_days' => :'handlingTimeDays',
        :'item_location' => :'itemLocation',
        :'item_location_zip' => :'itemLocationZip',
        :'item_location_country' => :'itemLocationCountry',
        :'declared_shipping_cost' => :'declaredShippingCost',
        :'return_policy_text' => :'returnPolicyText',
        :'last_drift_checked_at' => :'lastDriftCheckedAt',
        :'verification_failed' => :'verificationFailed',
        :'published_overrides' => :'publishedOverrides'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'user_id' => :'String',
        :'quantity' => :'Float',
        :'status' => :'String',
        :'platform' => :'String',
        :'error_message' => :'String',
        :'listing_id' => :'String',
        :'account_slot' => :'Float',
        :'delisted_at' => :'Time',
        :'sold_at' => :'Time',
        :'inventory_item_id' => :'String',
        :'platform_listing_id' => :'String',
        :'platform_listing_url' => :'String',
        :'stock_location' => :'String',
        :'listed_at' => :'Time',
        :'shared_at' => :'Time',
        :'delist_reason' => :'String',
        :'last_checked_at' => :'Time',
        :'views' => :'Float',
        :'favorites' => :'Float',
        :'comments_count' => :'Float',
        :'last_stats_synced_at' => :'Time',
        :'hashtags' => :'Array<String>',
        :'is_draft' => :'Boolean',
        :'scheduled_publish_at' => :'Time',
        :'is_dutch_auction' => :'Boolean',
        :'dutch_start_cents' => :'Float',
        :'dutch_floor_cents' => :'Float',
        :'dutch_ends_at' => :'Time',
        :'is_pre_order' => :'Boolean',
        :'expected_ship_by' => :'String',
        :'preorder_deposit_percent_bps' => :'Float',
        :'boosted_at' => :'Time',
        :'image_caption' => :'String',
        :'duration_days' => :'Float',
        :'ends_at' => :'Time',
        :'best_offer_enabled' => :'Boolean',
        :'best_offer_auto_accept_cents' => :'Float',
        :'best_offer_auto_decline_cents' => :'Float',
        :'aesthetic_tags' => :'Array<String>',
        :'allows_local_pickup' => :'Boolean',
        :'pickup_radius_miles' => :'Float',
        :'pickup_lat' => :'String',
        :'pickup_lng' => :'String',
        :'refurbished_tier' => :'String',
        :'charity_slug' => :'String',
        :'charity_percent_bps' => :'Float',
        :'crossly_return_policy_id' => :'String',
        :'crossly_shipping_policy_id' => :'String',
        :'crossly_payment_policy_id' => :'String',
        :'retail_price_cents' => :'Float',
        :'restricted_countries' => :'Array<String>',
        :'auction_extend_seconds' => :'Float',
        :'authentication_provider_slug' => :'String',
        :'authentication_required' => :'Boolean',
        :'has_variants' => :'Boolean',
        :'charity_id' => :'String',
        :'min_order_quantity' => :'Float',
        :'wholesale_unit_price_cents' => :'Float',
        :'wholesale_min_quantity' => :'Float',
        :'auction_reserve_cents' => :'Float',
        :'is_gtc' => :'Boolean',
        :'handling_time_days' => :'Float',
        :'item_location' => :'String',
        :'item_location_zip' => :'String',
        :'item_location_country' => :'String',
        :'declared_shipping_cost' => :'String',
        :'return_policy_text' => :'String',
        :'last_drift_checked_at' => :'Time',
        :'verification_failed' => :'Boolean',
        :'published_overrides' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'error_message',
        :'delisted_at',
        :'sold_at',
        :'inventory_item_id',
        :'platform_listing_url',
        :'listed_at',
        :'shared_at',
        :'delist_reason',
        :'last_checked_at',
        :'last_stats_synced_at',
        :'hashtags',
        :'scheduled_publish_at',
        :'dutch_start_cents',
        :'dutch_floor_cents',
        :'dutch_ends_at',
        :'expected_ship_by',
        :'preorder_deposit_percent_bps',
        :'boosted_at',
        :'image_caption',
        :'duration_days',
        :'ends_at',
        :'best_offer_auto_accept_cents',
        :'best_offer_auto_decline_cents',
        :'aesthetic_tags',
        :'pickup_radius_miles',
        :'pickup_lat',
        :'pickup_lng',
        :'refurbished_tier',
        :'charity_slug',
        :'charity_percent_bps',
        :'crossly_return_policy_id',
        :'crossly_shipping_policy_id',
        :'crossly_payment_policy_id',
        :'retail_price_cents',
        :'restricted_countries',
        :'auction_extend_seconds',
        :'authentication_provider_slug',
        :'charity_id',
        :'wholesale_unit_price_cents',
        :'wholesale_min_quantity',
        :'auction_reserve_cents',
        :'item_location',
        :'item_location_zip',
        :'item_location_country',
        :'declared_shipping_cost',
        :'return_policy_text',
        :'last_drift_checked_at',
        :'published_overrides'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crossly::GetListingResponsePlatformListings` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crossly::GetListingResponsePlatformListings`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'platform')
        self.platform = attributes[:'platform']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'listing_id')
        self.listing_id = attributes[:'listing_id']
      end

      if attributes.key?(:'account_slot')
        self.account_slot = attributes[:'account_slot']
      end

      if attributes.key?(:'delisted_at')
        self.delisted_at = attributes[:'delisted_at']
      end

      if attributes.key?(:'sold_at')
        self.sold_at = attributes[:'sold_at']
      end

      if attributes.key?(:'inventory_item_id')
        self.inventory_item_id = attributes[:'inventory_item_id']
      end

      if attributes.key?(:'platform_listing_id')
        self.platform_listing_id = attributes[:'platform_listing_id']
      end

      if attributes.key?(:'platform_listing_url')
        self.platform_listing_url = attributes[:'platform_listing_url']
      end

      if attributes.key?(:'stock_location')
        self.stock_location = attributes[:'stock_location']
      end

      if attributes.key?(:'listed_at')
        self.listed_at = attributes[:'listed_at']
      end

      if attributes.key?(:'shared_at')
        self.shared_at = attributes[:'shared_at']
      end

      if attributes.key?(:'delist_reason')
        self.delist_reason = attributes[:'delist_reason']
      end

      if attributes.key?(:'last_checked_at')
        self.last_checked_at = attributes[:'last_checked_at']
      end

      if attributes.key?(:'views')
        self.views = attributes[:'views']
      end

      if attributes.key?(:'favorites')
        self.favorites = attributes[:'favorites']
      end

      if attributes.key?(:'comments_count')
        self.comments_count = attributes[:'comments_count']
      end

      if attributes.key?(:'last_stats_synced_at')
        self.last_stats_synced_at = attributes[:'last_stats_synced_at']
      end

      if attributes.key?(:'hashtags')
        if (value = attributes[:'hashtags']).is_a?(Array)
          self.hashtags = value
        end
      end

      if attributes.key?(:'is_draft')
        self.is_draft = attributes[:'is_draft']
      end

      if attributes.key?(:'scheduled_publish_at')
        self.scheduled_publish_at = attributes[:'scheduled_publish_at']
      end

      if attributes.key?(:'is_dutch_auction')
        self.is_dutch_auction = attributes[:'is_dutch_auction']
      end

      if attributes.key?(:'dutch_start_cents')
        self.dutch_start_cents = attributes[:'dutch_start_cents']
      end

      if attributes.key?(:'dutch_floor_cents')
        self.dutch_floor_cents = attributes[:'dutch_floor_cents']
      end

      if attributes.key?(:'dutch_ends_at')
        self.dutch_ends_at = attributes[:'dutch_ends_at']
      end

      if attributes.key?(:'is_pre_order')
        self.is_pre_order = attributes[:'is_pre_order']
      end

      if attributes.key?(:'expected_ship_by')
        self.expected_ship_by = attributes[:'expected_ship_by']
      end

      if attributes.key?(:'preorder_deposit_percent_bps')
        self.preorder_deposit_percent_bps = attributes[:'preorder_deposit_percent_bps']
      end

      if attributes.key?(:'boosted_at')
        self.boosted_at = attributes[:'boosted_at']
      end

      if attributes.key?(:'image_caption')
        self.image_caption = attributes[:'image_caption']
      end

      if attributes.key?(:'duration_days')
        self.duration_days = attributes[:'duration_days']
      end

      if attributes.key?(:'ends_at')
        self.ends_at = attributes[:'ends_at']
      end

      if attributes.key?(:'best_offer_enabled')
        self.best_offer_enabled = attributes[:'best_offer_enabled']
      end

      if attributes.key?(:'best_offer_auto_accept_cents')
        self.best_offer_auto_accept_cents = attributes[:'best_offer_auto_accept_cents']
      end

      if attributes.key?(:'best_offer_auto_decline_cents')
        self.best_offer_auto_decline_cents = attributes[:'best_offer_auto_decline_cents']
      end

      if attributes.key?(:'aesthetic_tags')
        if (value = attributes[:'aesthetic_tags']).is_a?(Array)
          self.aesthetic_tags = value
        end
      end

      if attributes.key?(:'allows_local_pickup')
        self.allows_local_pickup = attributes[:'allows_local_pickup']
      end

      if attributes.key?(:'pickup_radius_miles')
        self.pickup_radius_miles = attributes[:'pickup_radius_miles']
      end

      if attributes.key?(:'pickup_lat')
        self.pickup_lat = attributes[:'pickup_lat']
      end

      if attributes.key?(:'pickup_lng')
        self.pickup_lng = attributes[:'pickup_lng']
      end

      if attributes.key?(:'refurbished_tier')
        self.refurbished_tier = attributes[:'refurbished_tier']
      end

      if attributes.key?(:'charity_slug')
        self.charity_slug = attributes[:'charity_slug']
      end

      if attributes.key?(:'charity_percent_bps')
        self.charity_percent_bps = attributes[:'charity_percent_bps']
      end

      if attributes.key?(:'crossly_return_policy_id')
        self.crossly_return_policy_id = attributes[:'crossly_return_policy_id']
      end

      if attributes.key?(:'crossly_shipping_policy_id')
        self.crossly_shipping_policy_id = attributes[:'crossly_shipping_policy_id']
      end

      if attributes.key?(:'crossly_payment_policy_id')
        self.crossly_payment_policy_id = attributes[:'crossly_payment_policy_id']
      end

      if attributes.key?(:'retail_price_cents')
        self.retail_price_cents = attributes[:'retail_price_cents']
      end

      if attributes.key?(:'restricted_countries')
        if (value = attributes[:'restricted_countries']).is_a?(Array)
          self.restricted_countries = value
        end
      end

      if attributes.key?(:'auction_extend_seconds')
        self.auction_extend_seconds = attributes[:'auction_extend_seconds']
      end

      if attributes.key?(:'authentication_provider_slug')
        self.authentication_provider_slug = attributes[:'authentication_provider_slug']
      end

      if attributes.key?(:'authentication_required')
        self.authentication_required = attributes[:'authentication_required']
      end

      if attributes.key?(:'has_variants')
        self.has_variants = attributes[:'has_variants']
      end

      if attributes.key?(:'charity_id')
        self.charity_id = attributes[:'charity_id']
      end

      if attributes.key?(:'min_order_quantity')
        self.min_order_quantity = attributes[:'min_order_quantity']
      end

      if attributes.key?(:'wholesale_unit_price_cents')
        self.wholesale_unit_price_cents = attributes[:'wholesale_unit_price_cents']
      end

      if attributes.key?(:'wholesale_min_quantity')
        self.wholesale_min_quantity = attributes[:'wholesale_min_quantity']
      end

      if attributes.key?(:'auction_reserve_cents')
        self.auction_reserve_cents = attributes[:'auction_reserve_cents']
      end

      if attributes.key?(:'is_gtc')
        self.is_gtc = attributes[:'is_gtc']
      end

      if attributes.key?(:'handling_time_days')
        self.handling_time_days = attributes[:'handling_time_days']
      end

      if attributes.key?(:'item_location')
        self.item_location = attributes[:'item_location']
      end

      if attributes.key?(:'item_location_zip')
        self.item_location_zip = attributes[:'item_location_zip']
      end

      if attributes.key?(:'item_location_country')
        self.item_location_country = attributes[:'item_location_country']
      end

      if attributes.key?(:'declared_shipping_cost')
        self.declared_shipping_cost = attributes[:'declared_shipping_cost']
      end

      if attributes.key?(:'return_policy_text')
        self.return_policy_text = attributes[:'return_policy_text']
      end

      if attributes.key?(:'last_drift_checked_at')
        self.last_drift_checked_at = attributes[:'last_drift_checked_at']
      end

      if attributes.key?(:'verification_failed')
        self.verification_failed = attributes[:'verification_failed']
      end

      if attributes.key?(:'published_overrides')
        self.published_overrides = attributes[:'published_overrides']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @platform.nil?
        invalid_properties.push('invalid value for "platform", platform cannot be nil.')
      end

      if @listing_id.nil?
        invalid_properties.push('invalid value for "listing_id", listing_id cannot be nil.')
      end

      if @account_slot.nil?
        invalid_properties.push('invalid value for "account_slot", account_slot cannot be nil.')
      end

      if @platform_listing_id.nil?
        invalid_properties.push('invalid value for "platform_listing_id", platform_listing_id cannot be nil.')
      end

      if @stock_location.nil?
        invalid_properties.push('invalid value for "stock_location", stock_location cannot be nil.')
      end

      if @views.nil?
        invalid_properties.push('invalid value for "views", views cannot be nil.')
      end

      if @favorites.nil?
        invalid_properties.push('invalid value for "favorites", favorites cannot be nil.')
      end

      if @comments_count.nil?
        invalid_properties.push('invalid value for "comments_count", comments_count cannot be nil.')
      end

      if @is_draft.nil?
        invalid_properties.push('invalid value for "is_draft", is_draft cannot be nil.')
      end

      if @is_dutch_auction.nil?
        invalid_properties.push('invalid value for "is_dutch_auction", is_dutch_auction cannot be nil.')
      end

      if @is_pre_order.nil?
        invalid_properties.push('invalid value for "is_pre_order", is_pre_order cannot be nil.')
      end

      if @best_offer_enabled.nil?
        invalid_properties.push('invalid value for "best_offer_enabled", best_offer_enabled cannot be nil.')
      end

      if @allows_local_pickup.nil?
        invalid_properties.push('invalid value for "allows_local_pickup", allows_local_pickup cannot be nil.')
      end

      if @authentication_required.nil?
        invalid_properties.push('invalid value for "authentication_required", authentication_required cannot be nil.')
      end

      if @has_variants.nil?
        invalid_properties.push('invalid value for "has_variants", has_variants cannot be nil.')
      end

      if @min_order_quantity.nil?
        invalid_properties.push('invalid value for "min_order_quantity", min_order_quantity cannot be nil.')
      end

      if @is_gtc.nil?
        invalid_properties.push('invalid value for "is_gtc", is_gtc cannot be nil.')
      end

      if @handling_time_days.nil?
        invalid_properties.push('invalid value for "handling_time_days", handling_time_days cannot be nil.')
      end

      if @verification_failed.nil?
        invalid_properties.push('invalid value for "verification_failed", verification_failed cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @user_id.nil?
      return false if @quantity.nil?
      return false if @status.nil?
      return false if @platform.nil?
      return false if @listing_id.nil?
      return false if @account_slot.nil?
      return false if @platform_listing_id.nil?
      return false if @stock_location.nil?
      return false if @views.nil?
      return false if @favorites.nil?
      return false if @comments_count.nil?
      return false if @is_draft.nil?
      return false if @is_dutch_auction.nil?
      return false if @is_pre_order.nil?
      return false if @best_offer_enabled.nil?
      return false if @allows_local_pickup.nil?
      return false if @authentication_required.nil?
      return false if @has_variants.nil?
      return false if @min_order_quantity.nil?
      return false if @is_gtc.nil?
      return false if @handling_time_days.nil?
      return false if @verification_failed.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          user_id == o.user_id &&
          quantity == o.quantity &&
          status == o.status &&
          platform == o.platform &&
          error_message == o.error_message &&
          listing_id == o.listing_id &&
          account_slot == o.account_slot &&
          delisted_at == o.delisted_at &&
          sold_at == o.sold_at &&
          inventory_item_id == o.inventory_item_id &&
          platform_listing_id == o.platform_listing_id &&
          platform_listing_url == o.platform_listing_url &&
          stock_location == o.stock_location &&
          listed_at == o.listed_at &&
          shared_at == o.shared_at &&
          delist_reason == o.delist_reason &&
          last_checked_at == o.last_checked_at &&
          views == o.views &&
          favorites == o.favorites &&
          comments_count == o.comments_count &&
          last_stats_synced_at == o.last_stats_synced_at &&
          hashtags == o.hashtags &&
          is_draft == o.is_draft &&
          scheduled_publish_at == o.scheduled_publish_at &&
          is_dutch_auction == o.is_dutch_auction &&
          dutch_start_cents == o.dutch_start_cents &&
          dutch_floor_cents == o.dutch_floor_cents &&
          dutch_ends_at == o.dutch_ends_at &&
          is_pre_order == o.is_pre_order &&
          expected_ship_by == o.expected_ship_by &&
          preorder_deposit_percent_bps == o.preorder_deposit_percent_bps &&
          boosted_at == o.boosted_at &&
          image_caption == o.image_caption &&
          duration_days == o.duration_days &&
          ends_at == o.ends_at &&
          best_offer_enabled == o.best_offer_enabled &&
          best_offer_auto_accept_cents == o.best_offer_auto_accept_cents &&
          best_offer_auto_decline_cents == o.best_offer_auto_decline_cents &&
          aesthetic_tags == o.aesthetic_tags &&
          allows_local_pickup == o.allows_local_pickup &&
          pickup_radius_miles == o.pickup_radius_miles &&
          pickup_lat == o.pickup_lat &&
          pickup_lng == o.pickup_lng &&
          refurbished_tier == o.refurbished_tier &&
          charity_slug == o.charity_slug &&
          charity_percent_bps == o.charity_percent_bps &&
          crossly_return_policy_id == o.crossly_return_policy_id &&
          crossly_shipping_policy_id == o.crossly_shipping_policy_id &&
          crossly_payment_policy_id == o.crossly_payment_policy_id &&
          retail_price_cents == o.retail_price_cents &&
          restricted_countries == o.restricted_countries &&
          auction_extend_seconds == o.auction_extend_seconds &&
          authentication_provider_slug == o.authentication_provider_slug &&
          authentication_required == o.authentication_required &&
          has_variants == o.has_variants &&
          charity_id == o.charity_id &&
          min_order_quantity == o.min_order_quantity &&
          wholesale_unit_price_cents == o.wholesale_unit_price_cents &&
          wholesale_min_quantity == o.wholesale_min_quantity &&
          auction_reserve_cents == o.auction_reserve_cents &&
          is_gtc == o.is_gtc &&
          handling_time_days == o.handling_time_days &&
          item_location == o.item_location &&
          item_location_zip == o.item_location_zip &&
          item_location_country == o.item_location_country &&
          declared_shipping_cost == o.declared_shipping_cost &&
          return_policy_text == o.return_policy_text &&
          last_drift_checked_at == o.last_drift_checked_at &&
          verification_failed == o.verification_failed &&
          published_overrides == o.published_overrides
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, user_id, quantity, status, platform, error_message, listing_id, account_slot, delisted_at, sold_at, inventory_item_id, platform_listing_id, platform_listing_url, stock_location, listed_at, shared_at, delist_reason, last_checked_at, views, favorites, comments_count, last_stats_synced_at, hashtags, is_draft, scheduled_publish_at, is_dutch_auction, dutch_start_cents, dutch_floor_cents, dutch_ends_at, is_pre_order, expected_ship_by, preorder_deposit_percent_bps, boosted_at, image_caption, duration_days, ends_at, best_offer_enabled, best_offer_auto_accept_cents, best_offer_auto_decline_cents, aesthetic_tags, allows_local_pickup, pickup_radius_miles, pickup_lat, pickup_lng, refurbished_tier, charity_slug, charity_percent_bps, crossly_return_policy_id, crossly_shipping_policy_id, crossly_payment_policy_id, retail_price_cents, restricted_countries, auction_extend_seconds, authentication_provider_slug, authentication_required, has_variants, charity_id, min_order_quantity, wholesale_unit_price_cents, wholesale_min_quantity, auction_reserve_cents, is_gtc, handling_time_days, item_location, item_location_zip, item_location_country, declared_shipping_cost, return_policy_text, last_drift_checked_at, verification_failed, published_overrides].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crossly.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
