=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module Crossly
  class ListMarketProductsItem
    attr_accessor :id

    attr_accessor :name

    attr_accessor :brand

    attr_accessor :model

    attr_accessor :category_slug

    attr_accessor :style_code

    attr_accessor :image_url

    attr_accessor :lowest_ask_cents_from

    attr_accessor :highest_bid_cents

    attr_accessor :last_sale_cents

    attr_accessor :trades_count

    attr_accessor :graded_grade_keys

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'brand' => :'brand',
        :'model' => :'model',
        :'category_slug' => :'categorySlug',
        :'style_code' => :'styleCode',
        :'image_url' => :'imageUrl',
        :'lowest_ask_cents_from' => :'lowestAskCentsFrom',
        :'highest_bid_cents' => :'highestBidCents',
        :'last_sale_cents' => :'lastSaleCents',
        :'trades_count' => :'tradesCount',
        :'graded_grade_keys' => :'gradedGradeKeys'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'brand' => :'String',
        :'model' => :'String',
        :'category_slug' => :'String',
        :'style_code' => :'String',
        :'image_url' => :'String',
        :'lowest_ask_cents_from' => :'Float',
        :'highest_bid_cents' => :'Float',
        :'last_sale_cents' => :'Float',
        :'trades_count' => :'Float',
        :'graded_grade_keys' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'brand',
        :'model',
        :'style_code',
        :'image_url',
        :'lowest_ask_cents_from',
        :'highest_bid_cents',
        :'last_sale_cents',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Crossly::ListMarketProductsItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Crossly::ListMarketProductsItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'category_slug')
        self.category_slug = attributes[:'category_slug']
      end

      if attributes.key?(:'style_code')
        self.style_code = attributes[:'style_code']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'lowest_ask_cents_from')
        self.lowest_ask_cents_from = attributes[:'lowest_ask_cents_from']
      end

      if attributes.key?(:'highest_bid_cents')
        self.highest_bid_cents = attributes[:'highest_bid_cents']
      end

      if attributes.key?(:'last_sale_cents')
        self.last_sale_cents = attributes[:'last_sale_cents']
      end

      if attributes.key?(:'trades_count')
        self.trades_count = attributes[:'trades_count']
      end

      if attributes.key?(:'graded_grade_keys')
        if (value = attributes[:'graded_grade_keys']).is_a?(Array)
          self.graded_grade_keys = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @category_slug.nil?
        invalid_properties.push('invalid value for "category_slug", category_slug cannot be nil.')
      end

      if @trades_count.nil?
        invalid_properties.push('invalid value for "trades_count", trades_count cannot be nil.')
      end

      if @graded_grade_keys.nil?
        invalid_properties.push('invalid value for "graded_grade_keys", graded_grade_keys cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @name.nil?
      return false if @category_slug.nil?
      return false if @trades_count.nil?
      return false if @graded_grade_keys.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          brand == o.brand &&
          model == o.model &&
          category_slug == o.category_slug &&
          style_code == o.style_code &&
          image_url == o.image_url &&
          lowest_ask_cents_from == o.lowest_ask_cents_from &&
          highest_bid_cents == o.highest_bid_cents &&
          last_sale_cents == o.last_sale_cents &&
          trades_count == o.trades_count &&
          graded_grade_keys == o.graded_grade_keys
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, brand, model, category_slug, style_code, image_url, lowest_ask_cents_from, highest_bid_cents, last_sale_cents, trades_count, graded_grade_keys].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Crossly.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
