=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'cgi'

module Crossly
  class CustomersApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Bulk blocklist customer handles.
    # @param [Hash] opts the optional parameters
    # @return [CreateCustomerBulkDeleteResponse]
    def create_customer_bulk_delete(opts = {})
      data, _status_code, _headers = create_customer_bulk_delete_with_http_info(opts)
      data
    end

    # Bulk blocklist customer handles.
    # @param [Hash] opts the optional parameters
    # @return [Array<(CreateCustomerBulkDeleteResponse, Integer, Hash)>] CreateCustomerBulkDeleteResponse data, response status code and response headers
    def create_customer_bulk_delete_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CustomersApi.create_customer_bulk_delete ...'
      end
      # resource path
      local_var_path = '/v1/customers/bulk-delete'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'CreateCustomerBulkDeleteResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PersonalAccessToken']

      new_options = opts.merge(
        :operation => :"CustomersApi.create_customer_bulk_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CustomersApi#create_customer_bulk_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Bulk export aggregated customers as CSV.
    # @param [Hash] opts the optional parameters
    # @return [String]
    def create_customer_bulk_export(opts = {})
      data, _status_code, _headers = create_customer_bulk_export_with_http_info(opts)
      data
    end

    # Bulk export aggregated customers as CSV.
    # @param [Hash] opts the optional parameters
    # @return [Array<(String, Integer, Hash)>] String data, response status code and response headers
    def create_customer_bulk_export_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CustomersApi.create_customer_bulk_export ...'
      end
      # resource path
      local_var_path = '/v1/customers/bulk-export'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'String'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PersonalAccessToken']

      new_options = opts.merge(
        :operation => :"CustomersApi.create_customer_bulk_export",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CustomersApi#create_customer_bulk_export\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get one customer with their recent 50 orders.
    # @param handle [String] 
    # @param [Hash] opts the optional parameters
    # @return [GetCustomerResponse]
    def get_customer(handle, opts = {})
      data, _status_code, _headers = get_customer_with_http_info(handle, opts)
      data
    end

    # Get one customer with their recent 50 orders.
    # @param handle [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(GetCustomerResponse, Integer, Hash)>] GetCustomerResponse data, response status code and response headers
    def get_customer_with_http_info(handle, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CustomersApi.get_customer ...'
      end
      # verify the required parameter 'handle' is set
      if @api_client.config.client_side_validation && handle.nil?
        fail ArgumentError, "Missing the required parameter 'handle' when calling CustomersApi.get_customer"
      end
      # resource path
      local_var_path = '/v1/customers/{handle}'.sub('{' + 'handle' + '}', CGI.escape(handle.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'GetCustomerResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PersonalAccessToken']

      new_options = opts.merge(
        :operation => :"CustomersApi.get_customer",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CustomersApi#get_customer\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List aggregated customers (group-by lower(buyer_username)).
    # @param [Hash] opts the optional parameters
    # @return [V1List]
    def list_customers(opts = {})
      data, _status_code, _headers = list_customers_with_http_info(opts)
      data
    end

    # List aggregated customers (group-by lower(buyer_username)).
    # @param [Hash] opts the optional parameters
    # @return [Array<(V1List, Integer, Hash)>] V1List data, response status code and response headers
    def list_customers_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CustomersApi.list_customers ...'
      end
      # resource path
      local_var_path = '/v1/customers'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'V1List'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['PersonalAccessToken']

      new_options = opts.merge(
        :operation => :"CustomersApi.list_customers",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CustomersApi#list_customers\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
