=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CrosslyBuyer
  class CreateCbxRedemptionQuoteResponse
    attr_accessor :service_kind

    attr_accessor :label

    attr_accessor :list_price_cents

    attr_accessor :charged_cents

    attr_accessor :discount_bps

    attr_accessor :base_units

    attr_accessor :cents_per_token

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'service_kind' => :'serviceKind',
        :'label' => :'label',
        :'list_price_cents' => :'listPriceCents',
        :'charged_cents' => :'chargedCents',
        :'discount_bps' => :'discountBps',
        :'base_units' => :'baseUnits',
        :'cents_per_token' => :'centsPerToken'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'service_kind' => :'String',
        :'label' => :'String',
        :'list_price_cents' => :'Float',
        :'charged_cents' => :'Float',
        :'discount_bps' => :'Float',
        :'base_units' => :'String',
        :'cents_per_token' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CrosslyBuyer::CreateCbxRedemptionQuoteResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CrosslyBuyer::CreateCbxRedemptionQuoteResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'service_kind')
        self.service_kind = attributes[:'service_kind']
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      end

      if attributes.key?(:'list_price_cents')
        self.list_price_cents = attributes[:'list_price_cents']
      end

      if attributes.key?(:'charged_cents')
        self.charged_cents = attributes[:'charged_cents']
      end

      if attributes.key?(:'discount_bps')
        self.discount_bps = attributes[:'discount_bps']
      end

      if attributes.key?(:'base_units')
        self.base_units = attributes[:'base_units']
      end

      if attributes.key?(:'cents_per_token')
        self.cents_per_token = attributes[:'cents_per_token']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @service_kind.nil?
        invalid_properties.push('invalid value for "service_kind", service_kind cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @list_price_cents.nil?
        invalid_properties.push('invalid value for "list_price_cents", list_price_cents cannot be nil.')
      end

      if @charged_cents.nil?
        invalid_properties.push('invalid value for "charged_cents", charged_cents cannot be nil.')
      end

      if @discount_bps.nil?
        invalid_properties.push('invalid value for "discount_bps", discount_bps cannot be nil.')
      end

      if @base_units.nil?
        invalid_properties.push('invalid value for "base_units", base_units cannot be nil.')
      end

      if @cents_per_token.nil?
        invalid_properties.push('invalid value for "cents_per_token", cents_per_token cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @service_kind.nil?
      service_kind_validator = EnumAttributeValidator.new('String', ["grading", "subscription", "authentication", "evidence_seal"])
      return false unless service_kind_validator.valid?(@service_kind)
      return false if @label.nil?
      return false if @list_price_cents.nil?
      return false if @charged_cents.nil?
      return false if @discount_bps.nil?
      return false if @base_units.nil?
      return false if @cents_per_token.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] service_kind Object to be assigned
    def service_kind=(service_kind)
      validator = EnumAttributeValidator.new('String', ["grading", "subscription", "authentication", "evidence_seal"])
      unless validator.valid?(service_kind)
        fail ArgumentError, "invalid value for \"service_kind\", must be one of #{validator.allowable_values}."
      end
      @service_kind = service_kind
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          service_kind == o.service_kind &&
          label == o.label &&
          list_price_cents == o.list_price_cents &&
          charged_cents == o.charged_cents &&
          discount_bps == o.discount_bps &&
          base_units == o.base_units &&
          cents_per_token == o.cents_per_token
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [service_kind, label, list_price_cents, charged_cents, discount_bps, base_units, cents_per_token].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CrosslyBuyer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
