=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CrosslyBuyer
  class GetMarketProductResponseProduct
    attr_accessor :id

    attr_accessor :brand

    attr_accessor :name

    attr_accessor :created_at

    attr_accessor :status

    attr_accessor :retail_cents

    attr_accessor :category_slug

    attr_accessor :external_id

    attr_accessor :image_url

    attr_accessor :model

    attr_accessor :colorway

    attr_accessor :style_code

    attr_accessor :release_date

    attr_accessor :submitted_by_user_id

    attr_accessor :approved_by_user_id

    attr_accessor :approved_at

    attr_accessor :rejection_reason

    attr_accessor :proposed_variants

    attr_accessor :verification

    attr_accessor :ai_verdict

    attr_accessor :submission_source

    attr_accessor :duplicate_of_sku_id

    attr_accessor :preferred_provider_slug

    attr_accessor :allow_pre_bid

    attr_accessor :pre_bid_opens_at

    attr_accessor :featured

    attr_accessor :external_source

    attr_accessor :external_synced_at

    attr_accessor :graded_grade_keys

    attr_accessor :lowest_ask_cents

    attr_accessor :highest_bid_cents

    attr_accessor :last_sale_cents

    attr_accessor :trades_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'brand' => :'brand',
        :'name' => :'name',
        :'created_at' => :'createdAt',
        :'status' => :'status',
        :'retail_cents' => :'retailCents',
        :'category_slug' => :'categorySlug',
        :'external_id' => :'externalId',
        :'image_url' => :'imageUrl',
        :'model' => :'model',
        :'colorway' => :'colorway',
        :'style_code' => :'styleCode',
        :'release_date' => :'releaseDate',
        :'submitted_by_user_id' => :'submittedByUserId',
        :'approved_by_user_id' => :'approvedByUserId',
        :'approved_at' => :'approvedAt',
        :'rejection_reason' => :'rejectionReason',
        :'proposed_variants' => :'proposedVariants',
        :'verification' => :'verification',
        :'ai_verdict' => :'aiVerdict',
        :'submission_source' => :'submissionSource',
        :'duplicate_of_sku_id' => :'duplicateOfSkuId',
        :'preferred_provider_slug' => :'preferredProviderSlug',
        :'allow_pre_bid' => :'allowPreBid',
        :'pre_bid_opens_at' => :'preBidOpensAt',
        :'featured' => :'featured',
        :'external_source' => :'externalSource',
        :'external_synced_at' => :'externalSyncedAt',
        :'graded_grade_keys' => :'gradedGradeKeys',
        :'lowest_ask_cents' => :'lowestAskCents',
        :'highest_bid_cents' => :'highestBidCents',
        :'last_sale_cents' => :'lastSaleCents',
        :'trades_count' => :'tradesCount'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'brand' => :'String',
        :'name' => :'String',
        :'created_at' => :'Time',
        :'status' => :'String',
        :'retail_cents' => :'Float',
        :'category_slug' => :'String',
        :'external_id' => :'String',
        :'image_url' => :'String',
        :'model' => :'String',
        :'colorway' => :'String',
        :'style_code' => :'String',
        :'release_date' => :'String',
        :'submitted_by_user_id' => :'String',
        :'approved_by_user_id' => :'String',
        :'approved_at' => :'Time',
        :'rejection_reason' => :'String',
        :'proposed_variants' => :'Array<GetMarketProductResponseProductProposedVariants>',
        :'verification' => :'Object',
        :'ai_verdict' => :'Object',
        :'submission_source' => :'String',
        :'duplicate_of_sku_id' => :'String',
        :'preferred_provider_slug' => :'String',
        :'allow_pre_bid' => :'Boolean',
        :'pre_bid_opens_at' => :'Time',
        :'featured' => :'Boolean',
        :'external_source' => :'String',
        :'external_synced_at' => :'Time',
        :'graded_grade_keys' => :'Array<String>',
        :'lowest_ask_cents' => :'Float',
        :'highest_bid_cents' => :'Float',
        :'last_sale_cents' => :'Float',
        :'trades_count' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'brand',
        :'retail_cents',
        :'external_id',
        :'image_url',
        :'model',
        :'colorway',
        :'style_code',
        :'release_date',
        :'submitted_by_user_id',
        :'approved_by_user_id',
        :'approved_at',
        :'rejection_reason',
        :'ai_verdict',
        :'submission_source',
        :'duplicate_of_sku_id',
        :'preferred_provider_slug',
        :'pre_bid_opens_at',
        :'external_source',
        :'external_synced_at',
        :'lowest_ask_cents',
        :'highest_bid_cents',
        :'last_sale_cents',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CrosslyBuyer::GetMarketProductResponseProduct` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CrosslyBuyer::GetMarketProductResponseProduct`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'brand')
        self.brand = attributes[:'brand']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'retail_cents')
        self.retail_cents = attributes[:'retail_cents']
      end

      if attributes.key?(:'category_slug')
        self.category_slug = attributes[:'category_slug']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'colorway')
        self.colorway = attributes[:'colorway']
      end

      if attributes.key?(:'style_code')
        self.style_code = attributes[:'style_code']
      end

      if attributes.key?(:'release_date')
        self.release_date = attributes[:'release_date']
      end

      if attributes.key?(:'submitted_by_user_id')
        self.submitted_by_user_id = attributes[:'submitted_by_user_id']
      end

      if attributes.key?(:'approved_by_user_id')
        self.approved_by_user_id = attributes[:'approved_by_user_id']
      end

      if attributes.key?(:'approved_at')
        self.approved_at = attributes[:'approved_at']
      end

      if attributes.key?(:'rejection_reason')
        self.rejection_reason = attributes[:'rejection_reason']
      end

      if attributes.key?(:'proposed_variants')
        if (value = attributes[:'proposed_variants']).is_a?(Array)
          self.proposed_variants = value
        end
      end

      if attributes.key?(:'verification')
        self.verification = attributes[:'verification']
      end

      if attributes.key?(:'ai_verdict')
        self.ai_verdict = attributes[:'ai_verdict']
      end

      if attributes.key?(:'submission_source')
        self.submission_source = attributes[:'submission_source']
      end

      if attributes.key?(:'duplicate_of_sku_id')
        self.duplicate_of_sku_id = attributes[:'duplicate_of_sku_id']
      end

      if attributes.key?(:'preferred_provider_slug')
        self.preferred_provider_slug = attributes[:'preferred_provider_slug']
      end

      if attributes.key?(:'allow_pre_bid')
        self.allow_pre_bid = attributes[:'allow_pre_bid']
      end

      if attributes.key?(:'pre_bid_opens_at')
        self.pre_bid_opens_at = attributes[:'pre_bid_opens_at']
      end

      if attributes.key?(:'featured')
        self.featured = attributes[:'featured']
      end

      if attributes.key?(:'external_source')
        self.external_source = attributes[:'external_source']
      end

      if attributes.key?(:'external_synced_at')
        self.external_synced_at = attributes[:'external_synced_at']
      end

      if attributes.key?(:'graded_grade_keys')
        if (value = attributes[:'graded_grade_keys']).is_a?(Array)
          self.graded_grade_keys = value
        end
      end

      if attributes.key?(:'lowest_ask_cents')
        self.lowest_ask_cents = attributes[:'lowest_ask_cents']
      end

      if attributes.key?(:'highest_bid_cents')
        self.highest_bid_cents = attributes[:'highest_bid_cents']
      end

      if attributes.key?(:'last_sale_cents')
        self.last_sale_cents = attributes[:'last_sale_cents']
      end

      if attributes.key?(:'trades_count')
        self.trades_count = attributes[:'trades_count']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @category_slug.nil?
        invalid_properties.push('invalid value for "category_slug", category_slug cannot be nil.')
      end

      if @proposed_variants.nil?
        invalid_properties.push('invalid value for "proposed_variants", proposed_variants cannot be nil.')
      end

      if @verification.nil?
        invalid_properties.push('invalid value for "verification", verification cannot be nil.')
      end

      if @allow_pre_bid.nil?
        invalid_properties.push('invalid value for "allow_pre_bid", allow_pre_bid cannot be nil.')
      end

      if @featured.nil?
        invalid_properties.push('invalid value for "featured", featured cannot be nil.')
      end

      if @graded_grade_keys.nil?
        invalid_properties.push('invalid value for "graded_grade_keys", graded_grade_keys cannot be nil.')
      end

      if @trades_count.nil?
        invalid_properties.push('invalid value for "trades_count", trades_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @name.nil?
      return false if @created_at.nil?
      return false if @status.nil?
      return false if @category_slug.nil?
      return false if @proposed_variants.nil?
      return false if @verification.nil?
      return false if @allow_pre_bid.nil?
      return false if @featured.nil?
      return false if @graded_grade_keys.nil?
      return false if @trades_count.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          brand == o.brand &&
          name == o.name &&
          created_at == o.created_at &&
          status == o.status &&
          retail_cents == o.retail_cents &&
          category_slug == o.category_slug &&
          external_id == o.external_id &&
          image_url == o.image_url &&
          model == o.model &&
          colorway == o.colorway &&
          style_code == o.style_code &&
          release_date == o.release_date &&
          submitted_by_user_id == o.submitted_by_user_id &&
          approved_by_user_id == o.approved_by_user_id &&
          approved_at == o.approved_at &&
          rejection_reason == o.rejection_reason &&
          proposed_variants == o.proposed_variants &&
          verification == o.verification &&
          ai_verdict == o.ai_verdict &&
          submission_source == o.submission_source &&
          duplicate_of_sku_id == o.duplicate_of_sku_id &&
          preferred_provider_slug == o.preferred_provider_slug &&
          allow_pre_bid == o.allow_pre_bid &&
          pre_bid_opens_at == o.pre_bid_opens_at &&
          featured == o.featured &&
          external_source == o.external_source &&
          external_synced_at == o.external_synced_at &&
          graded_grade_keys == o.graded_grade_keys &&
          lowest_ask_cents == o.lowest_ask_cents &&
          highest_bid_cents == o.highest_bid_cents &&
          last_sale_cents == o.last_sale_cents &&
          trades_count == o.trades_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, brand, name, created_at, status, retail_cents, category_slug, external_id, image_url, model, colorway, style_code, release_date, submitted_by_user_id, approved_by_user_id, approved_at, rejection_reason, proposed_variants, verification, ai_verdict, submission_source, duplicate_of_sku_id, preferred_provider_slug, allow_pre_bid, pre_bid_opens_at, featured, external_source, external_synced_at, graded_grade_keys, lowest_ask_cents, highest_bid_cents, last_sale_cents, trades_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CrosslyBuyer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
