=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CrosslyBuyer
  class GetConnectionHealthResponseLiveness
    # The clean \"the browser pushed cookies\" signal.
    attr_accessor :last_browser_push_at

    attr_accessor :last_browser_push_ago

    # Also stamped by the executor on any successful server-side call, so it is NOT evidence the extension is alive. Exposed for debugging only.
    attr_accessor :last_synced_at

    # Last server-exec attempt, success or fail.
    attr_accessor :last_used_at

    attr_accessor :last_used_ago

    attr_accessor :auth_failure_streak

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'last_browser_push_at' => :'lastBrowserPushAt',
        :'last_browser_push_ago' => :'lastBrowserPushAgo',
        :'last_synced_at' => :'lastSyncedAt',
        :'last_used_at' => :'lastUsedAt',
        :'last_used_ago' => :'lastUsedAgo',
        :'auth_failure_streak' => :'authFailureStreak'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'last_browser_push_at' => :'String',
        :'last_browser_push_ago' => :'String',
        :'last_synced_at' => :'String',
        :'last_used_at' => :'String',
        :'last_used_ago' => :'String',
        :'auth_failure_streak' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'last_browser_push_at',
        :'last_synced_at',
        :'last_used_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CrosslyBuyer::GetConnectionHealthResponseLiveness` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CrosslyBuyer::GetConnectionHealthResponseLiveness`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'last_browser_push_at')
        self.last_browser_push_at = attributes[:'last_browser_push_at']
      end

      if attributes.key?(:'last_browser_push_ago')
        self.last_browser_push_ago = attributes[:'last_browser_push_ago']
      end

      if attributes.key?(:'last_synced_at')
        self.last_synced_at = attributes[:'last_synced_at']
      end

      if attributes.key?(:'last_used_at')
        self.last_used_at = attributes[:'last_used_at']
      end

      if attributes.key?(:'last_used_ago')
        self.last_used_ago = attributes[:'last_used_ago']
      end

      if attributes.key?(:'auth_failure_streak')
        self.auth_failure_streak = attributes[:'auth_failure_streak']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @last_browser_push_ago.nil?
        invalid_properties.push('invalid value for "last_browser_push_ago", last_browser_push_ago cannot be nil.')
      end

      if @last_used_ago.nil?
        invalid_properties.push('invalid value for "last_used_ago", last_used_ago cannot be nil.')
      end

      if @auth_failure_streak.nil?
        invalid_properties.push('invalid value for "auth_failure_streak", auth_failure_streak cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @last_browser_push_ago.nil?
      return false if @last_used_ago.nil?
      return false if @auth_failure_streak.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          last_browser_push_at == o.last_browser_push_at &&
          last_browser_push_ago == o.last_browser_push_ago &&
          last_synced_at == o.last_synced_at &&
          last_used_at == o.last_used_at &&
          last_used_ago == o.last_used_ago &&
          auth_failure_streak == o.auth_failure_streak
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [last_browser_push_at, last_browser_push_ago, last_synced_at, last_used_at, last_used_ago, auth_failure_streak].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CrosslyBuyer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
