=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CrosslyBuyer
  class InlineObject4
    attr_accessor :namespace

    attr_accessor :value

    attr_accessor :retail_host

    attr_accessor :page_price_cents

    attr_accessor :page_currency

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'namespace' => :'namespace',
        :'value' => :'value',
        :'retail_host' => :'retailHost',
        :'page_price_cents' => :'pagePriceCents',
        :'page_currency' => :'pageCurrency'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'namespace' => :'String',
        :'value' => :'String',
        :'retail_host' => :'String',
        :'page_price_cents' => :'Integer',
        :'page_currency' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CrosslyBuyer::InlineObject4` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CrosslyBuyer::InlineObject4`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'namespace')
        self.namespace = attributes[:'namespace']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      end

      if attributes.key?(:'retail_host')
        self.retail_host = attributes[:'retail_host']
      end

      if attributes.key?(:'page_price_cents')
        self.page_price_cents = attributes[:'page_price_cents']
      end

      if attributes.key?(:'page_currency')
        self.page_currency = attributes[:'page_currency']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @namespace.nil?
        invalid_properties.push('invalid value for "namespace", namespace cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      if !@page_price_cents.nil? && @page_price_cents < 0
        invalid_properties.push('invalid value for "page_price_cents", must be greater than or equal to 0.')
      end

      if !@page_currency.nil? && @page_currency.to_s.length > 3
        invalid_properties.push('invalid value for "page_currency", the character length must be smaller than or equal to 3.')
      end

      if !@page_currency.nil? && @page_currency.to_s.length < 3
        invalid_properties.push('invalid value for "page_currency", the character length must be great than or equal to 3.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @namespace.nil?
      namespace_validator = EnumAttributeValidator.new('String', ["gtin", "style_code", "lego_set", "tcgplayer", "discogs", "asin"])
      return false unless namespace_validator.valid?(@namespace)
      return false if @value.nil?
      return false if !@page_price_cents.nil? && @page_price_cents < 0
      return false if !@page_currency.nil? && @page_currency.to_s.length > 3
      return false if !@page_currency.nil? && @page_currency.to_s.length < 3
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] namespace Object to be assigned
    def namespace=(namespace)
      validator = EnumAttributeValidator.new('String', ["gtin", "style_code", "lego_set", "tcgplayer", "discogs", "asin"])
      unless validator.valid?(namespace)
        fail ArgumentError, "invalid value for \"namespace\", must be one of #{validator.allowable_values}."
      end
      @namespace = namespace
    end

    # Custom attribute writer method with validation
    # @param [Object] page_price_cents Value to be assigned
    def page_price_cents=(page_price_cents)
      if !page_price_cents.nil? && page_price_cents < 0
        fail ArgumentError, 'invalid value for "page_price_cents", must be greater than or equal to 0.'
      end

      @page_price_cents = page_price_cents
    end

    # Custom attribute writer method with validation
    # @param [Object] page_currency Value to be assigned
    def page_currency=(page_currency)
      if !page_currency.nil? && page_currency.to_s.length > 3
        fail ArgumentError, 'invalid value for "page_currency", the character length must be smaller than or equal to 3.'
      end

      if !page_currency.nil? && page_currency.to_s.length < 3
        fail ArgumentError, 'invalid value for "page_currency", the character length must be great than or equal to 3.'
      end

      @page_currency = page_currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          namespace == o.namespace &&
          value == o.value &&
          retail_host == o.retail_host &&
          page_price_cents == o.page_price_cents &&
          page_currency == o.page_currency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [namespace, value, retail_host, page_price_cents, page_currency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CrosslyBuyer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
