=begin
#Crossly Buyer API

#The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module CrosslyBuyer
  class ListSalesItem
    attr_accessor :id

    attr_accessor :user_id

    attr_accessor :platform

    attr_accessor :cancelled_at

    attr_accessor :order_id

    attr_accessor :listing_id

    attr_accessor :inventory_item_id

    attr_accessor :platform_listing_id

    attr_accessor :platform_order_id

    attr_accessor :cost_of_goods

    attr_accessor :deleted_at

    attr_accessor :sale_price

    attr_accessor :platform_fee

    attr_accessor :shipping_cost

    attr_accessor :net_profit

    attr_accessor :tax_collected

    attr_accessor :shipping_charged

    attr_accessor :fee_source

    attr_accessor :detected_by

    attr_accessor :detected_at

    attr_accessor :documents

    attr_accessor :refunded_amount

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'user_id' => :'userId',
        :'platform' => :'platform',
        :'cancelled_at' => :'cancelledAt',
        :'order_id' => :'orderId',
        :'listing_id' => :'listingId',
        :'inventory_item_id' => :'inventoryItemId',
        :'platform_listing_id' => :'platformListingId',
        :'platform_order_id' => :'platformOrderId',
        :'cost_of_goods' => :'costOfGoods',
        :'deleted_at' => :'deletedAt',
        :'sale_price' => :'salePrice',
        :'platform_fee' => :'platformFee',
        :'shipping_cost' => :'shippingCost',
        :'net_profit' => :'netProfit',
        :'tax_collected' => :'taxCollected',
        :'shipping_charged' => :'shippingCharged',
        :'fee_source' => :'feeSource',
        :'detected_by' => :'detectedBy',
        :'detected_at' => :'detectedAt',
        :'documents' => :'documents',
        :'refunded_amount' => :'refundedAmount'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'user_id' => :'String',
        :'platform' => :'String',
        :'cancelled_at' => :'Time',
        :'order_id' => :'String',
        :'listing_id' => :'String',
        :'inventory_item_id' => :'String',
        :'platform_listing_id' => :'String',
        :'platform_order_id' => :'String',
        :'cost_of_goods' => :'String',
        :'deleted_at' => :'Time',
        :'sale_price' => :'String',
        :'platform_fee' => :'String',
        :'shipping_cost' => :'String',
        :'net_profit' => :'String',
        :'tax_collected' => :'String',
        :'shipping_charged' => :'String',
        :'fee_source' => :'String',
        :'detected_by' => :'String',
        :'detected_at' => :'Time',
        :'documents' => :'Array<ListSalesItemDocuments>',
        :'refunded_amount' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'cancelled_at',
        :'order_id',
        :'listing_id',
        :'inventory_item_id',
        :'platform_listing_id',
        :'platform_order_id',
        :'cost_of_goods',
        :'deleted_at',
        :'sale_price',
        :'platform_fee',
        :'shipping_cost',
        :'net_profit',
        :'tax_collected',
        :'shipping_charged',
        :'fee_source',
        :'documents',
        :'refunded_amount'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `CrosslyBuyer::ListSalesItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `CrosslyBuyer::ListSalesItem`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'platform')
        self.platform = attributes[:'platform']
      end

      if attributes.key?(:'cancelled_at')
        self.cancelled_at = attributes[:'cancelled_at']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      end

      if attributes.key?(:'listing_id')
        self.listing_id = attributes[:'listing_id']
      end

      if attributes.key?(:'inventory_item_id')
        self.inventory_item_id = attributes[:'inventory_item_id']
      end

      if attributes.key?(:'platform_listing_id')
        self.platform_listing_id = attributes[:'platform_listing_id']
      end

      if attributes.key?(:'platform_order_id')
        self.platform_order_id = attributes[:'platform_order_id']
      end

      if attributes.key?(:'cost_of_goods')
        self.cost_of_goods = attributes[:'cost_of_goods']
      end

      if attributes.key?(:'deleted_at')
        self.deleted_at = attributes[:'deleted_at']
      end

      if attributes.key?(:'sale_price')
        self.sale_price = attributes[:'sale_price']
      end

      if attributes.key?(:'platform_fee')
        self.platform_fee = attributes[:'platform_fee']
      end

      if attributes.key?(:'shipping_cost')
        self.shipping_cost = attributes[:'shipping_cost']
      end

      if attributes.key?(:'net_profit')
        self.net_profit = attributes[:'net_profit']
      end

      if attributes.key?(:'tax_collected')
        self.tax_collected = attributes[:'tax_collected']
      end

      if attributes.key?(:'shipping_charged')
        self.shipping_charged = attributes[:'shipping_charged']
      end

      if attributes.key?(:'fee_source')
        self.fee_source = attributes[:'fee_source']
      end

      if attributes.key?(:'detected_by')
        self.detected_by = attributes[:'detected_by']
      end

      if attributes.key?(:'detected_at')
        self.detected_at = attributes[:'detected_at']
      end

      if attributes.key?(:'documents')
        if (value = attributes[:'documents']).is_a?(Array)
          self.documents = value
        end
      end

      if attributes.key?(:'refunded_amount')
        self.refunded_amount = attributes[:'refunded_amount']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @platform.nil?
        invalid_properties.push('invalid value for "platform", platform cannot be nil.')
      end

      if @detected_by.nil?
        invalid_properties.push('invalid value for "detected_by", detected_by cannot be nil.')
      end

      if @detected_at.nil?
        invalid_properties.push('invalid value for "detected_at", detected_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @user_id.nil?
      return false if @platform.nil?
      return false if @detected_by.nil?
      return false if @detected_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          user_id == o.user_id &&
          platform == o.platform &&
          cancelled_at == o.cancelled_at &&
          order_id == o.order_id &&
          listing_id == o.listing_id &&
          inventory_item_id == o.inventory_item_id &&
          platform_listing_id == o.platform_listing_id &&
          platform_order_id == o.platform_order_id &&
          cost_of_goods == o.cost_of_goods &&
          deleted_at == o.deleted_at &&
          sale_price == o.sale_price &&
          platform_fee == o.platform_fee &&
          shipping_cost == o.shipping_cost &&
          net_profit == o.net_profit &&
          tax_collected == o.tax_collected &&
          shipping_charged == o.shipping_charged &&
          fee_source == o.fee_source &&
          detected_by == o.detected_by &&
          detected_at == o.detected_at &&
          documents == o.documents &&
          refunded_amount == o.refunded_amount
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, user_id, platform, cancelled_at, order_id, listing_id, inventory_item_id, platform_listing_id, platform_order_id, cost_of_goods, deleted_at, sale_price, platform_fee, shipping_cost, net_profit, tax_collected, shipping_charged, fee_source, detected_by, detected_at, documents, refunded_amount].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = CrosslyBuyer.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
