=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crossly::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = Crossly::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(Crossly::AccountApi)
    end
  end

  # unit tests for create_account_cancel_deletion
  # Cancel a pending account deletion.
  # @param [Hash] opts the optional parameters
  # @return [CreateAccountCancelDeletionResponse]
  describe 'create_account_cancel_deletion test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_account_logout_all
  # Revoke every browser auth session for this user.
  # @param [Hash] opts the optional parameters
  # @return [CreateAccountLogoutAllResponse]
  describe 'create_account_logout_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_account_request_deletion
  # Schedule account deletion after a grace period.
  # @param [Hash] opts the optional parameters
  # @return [CreateAccountRequestDeletionResponse]
  describe 'create_account_request_deletion test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_auth_session
  # Revoke all active browser sessions.
  # @param [Hash] opts the optional parameters
  # @return [DeleteAuthSessionResponse]
  describe 'delete_auth_session test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_auth_session_by_session_id
  # Revoke a single browser session by id.
  # @param session_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteAuthSessionBySessionIdResponse]
  describe 'delete_auth_session_by_session_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_connected_app
  # Disconnect a third-party app. Its tokens stop working immediately.
  # @param grant_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteConnectedAppResponse]
  describe 'delete_connected_app test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_deletion_status
  # Get the currently-pending deletion request, if any.
  # @param [Hash] opts the optional parameters
  # @return [GetAccountDeletionStatusResponse]
  describe 'get_account_deletion_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_me
  # Identity check — authenticated user + PAT scopes + account state.
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_me test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_auth_sessions
  # List active browser auth sessions.
  # @param [Hash] opts the optional parameters
  # @return [V1List]
  describe 'list_auth_sessions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_connected_apps
  # List third-party OAuth apps with access to this account.
  # @param [Hash] opts the optional parameters
  # @return [V1List]
  describe 'list_connected_apps test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
