=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crossly::AIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AIApi' do
  before do
    # run before each test
    @api_instance = Crossly::AIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AIApi' do
    it 'should create an instance of AIApi' do
      expect(@api_instance).to be_instance_of(Crossly::AIApi)
    end
  end

  # unit tests for create_ai_categorize
  # Taxonomy guess from a single image URL.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiCategorizeResponse]
  describe 'create_ai_categorize test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_categorize_from_image
  # Taxonomy guess from a single base64 image.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiCategorizeFromImageResponse]
  describe 'create_ai_categorize_from_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_enhance_description
  # SEO-rewrite a listing description.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiEnhanceDescriptionResponse]
  describe 'create_ai_enhance_description test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_enhance_listing
  # Rewrite title + description + tags in one call.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiEnhanceListingResponse]
  describe 'create_ai_enhance_listing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_enhance_title
  # SEO-rewrite a listing title.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiEnhanceTitleResponse]
  describe 'create_ai_enhance_title test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_extract_receipt
  # Structured data extraction from a receipt photo.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiExtractReceiptResponse]
  describe 'create_ai_extract_receipt test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_generate_listing
  # Generate full listing fields from up to 4 image URLs.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiGenerateListingResponse]
  describe 'create_ai_generate_listing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_help
  # In-app help Q&amp;A grounded in supplied docs.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiHelpResponse]
  describe 'create_ai_help test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_magic_listing
  # Generate full listing fields from base64 photos.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiMagicListingResponse]
  describe 'create_ai_magic_listing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_ai_test_key
  # Live-ping a candidate BYO-key.
  # @param [Hash] opts the optional parameters
  # @return [CreateAiTestKeyResponse]
  describe 'create_ai_test_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_ai_key
  # Remove the BYO-key for a provider.
  # @param [Hash] opts the optional parameters
  # @return [DeleteAiKeyResponse]
  describe 'delete_ai_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ai_provider
  # Static catalog of supported AI providers.
  # @param [Hash] opts the optional parameters
  # @return [GetAiProviderResponse]
  describe 'get_ai_provider test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ai_status
  # BYO-key state for the calling user.
  # @param [Hash] opts the optional parameters
  # @return [GetAiStatusResponse]
  describe 'get_ai_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_ai_key
  # Save an encrypted BYO-key for an AI provider.
  # @param [Hash] opts the optional parameters
  # @return [UpdateAiKeyResponse]
  describe 'update_ai_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
