=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crossly::IntegrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IntegrationsApi' do
  before do
    # run before each test
    @api_instance = Crossly::IntegrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IntegrationsApi' do
    it 'should create an instance of IntegrationsApi' do
      expect(@api_instance).to be_instance_of(Crossly::IntegrationsApi)
    end
  end

  # unit tests for create_notification_integration
  # Add a Slack/Discord/Webhook destination.
  # @param [Hash] opts the optional parameters
  # @return [CreateNotificationIntegrationResponse]
  describe 'create_notification_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_notification_integration_test
  # Fire a canned test message to a notification destination.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CreateNotificationIntegrationTestResponse]
  describe 'create_notification_integration_test test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_notification_integration
  # Delete a notification destination.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteNotificationIntegrationResponse]
  describe 'delete_notification_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_notification_integrations
  # List Slack/Discord/Webhook destinations for notify.* automation actions.
  # @param [Hash] opts the optional parameters
  # @return [V1List]
  describe 'list_notification_integrations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_notification_integration
  # Edit a notification destination.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UpdateNotificationIntegrationResponse]
  describe 'update_notification_integration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
