=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crossly::PayoutApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayoutApi' do
  before do
    # run before each test
    @api_instance = Crossly::PayoutApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayoutApi' do
    it 'should create an instance of PayoutApi' do
      expect(@api_instance).to be_instance_of(Crossly::PayoutApi)
    end
  end

  # unit tests for get_payout_estimate
  # What one platform nets at a given price, after fees and shipping.
  # @param [Hash] opts the optional parameters
  # @return [GetPayoutEstimateResponse]
  describe 'get_payout_estimate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payout_gross_for_net
  # The gross price needed to clear a target net on one platform.
  # @param [Hash] opts the optional parameters
  # @return [GetPayoutGrossForNetResponse]
  describe 'get_payout_gross_for_net test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_payout_compare
  # Rank platforms by what they net at a given price. Defaults to connected ones.
  # @param [Hash] opts the optional parameters
  # @return [V1List]
  describe 'list_payout_compare test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
