=begin
#Crossly Seller API

#The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Crossly::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = Crossly::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(Crossly::WebhooksApi)
    end
  end

  # unit tests for create_webhook
  # Register a webhook endpoint (returns the signing secret once).
  # @param [Hash] opts the optional parameters
  # @return [CreateWebhookResponse]
  describe 'create_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_webhook_test
  # Fire a synthetic test.ping delivery to one webhook.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CreateWebhookTestResponse]
  describe 'create_webhook_test test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_webhook
  # Delete a webhook endpoint.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteWebhookResponse]
  describe 'delete_webhook test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhook_stream
  # Stream this account&#39;s webhook events as they happen (SSE).
  # A long-lived text/event-stream. Each event is one &#x60;data:&#x60; line of JSON: {eventName, eventId, createdAt, payload}. Used by &#x60;crossly dev&#x60; to forward live events to a local URL without exposing the machine to the internet. Does not replay history — you see what happens from the moment you connect.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_webhook_stream test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_webhooks
  # List your registered webhook endpoints.
  # @param [Hash] opts the optional parameters
  # @return [V1List]
  describe 'list_webhooks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
